# Generated by Django 4.2.2 on 2023-06-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventdeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('eventDisplay', models.CharField(max_length=100)),
                ('eventStartDate', models.DateTimeField()),
                ('eventEndDate', models.DateTimeField()),
                ('eventAddress', models.CharField(max_length=50)),
                ('eventCity', models.CharField(max_length=50)),
                ('eventState', models.CharField(max_length=50)),
                ('eventCountry', models.CharField(max_length=50)),
                ('eventZip', models.IntegerField()),
                ('eventDescription', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketname', models.CharField(max_length=50)),
                ('ticketprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticketCount', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.eventdeatils')),
            ],
        ),
    ]
