# Generated by Django 4.2.2 on 2023-06-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventdeatils',
            new_name='Eventdetails',
        ),
    ]
