# Generated by Django 4.2.2 on 2023-06-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_rename_eventdeatils_eventdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketprice',
            field=models.PositiveIntegerField(),
        ),
    ]
