# Generated by Django 4.2.2 on 2023-06-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_alter_ticket_ticketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketprice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
