# Generated by Django 4.2.2 on 2023-07-09 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0005_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='event',
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
