# Generated by Django 4.2.2 on 2023-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0006_remove_organizer_event_organizer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="organizerContact",
            field=models.IntegerField(),
        ),
    ]
