# Generated by Django 4.2.2 on 2023-07-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0007_alter_organizer_organizercontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="organizerContact",
            field=models.CharField(max_length=15),
        ),
    ]
