# Generated by Django 4.2.2 on 2023-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0008_alter_organizer_organizercontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankAccount",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankIFSC",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerContact",
            field=models.CharField(max_length=50),
        ),
    ]
