# Generated by Django 4.2.2 on 2023-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0009_alter_organizer_organizerbankaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="organizerAddress",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankAccount",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankBranch",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankIFSC",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankName",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerContact",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerName",
            field=models.CharField(max_length=500),
        ),
    ]
