# Generated by Django 4.2.2 on 2023-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0011_alter_organizer_organizeraddress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="organizerAddress",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankAccount",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankBranch",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankIFSC",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerBankName",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerContact",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerEmail",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="organizerName",
            field=models.TextField(),
        ),
    ]
