# Generated by Django 4.2.2 on 2023-07-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0012_alter_organizer_organizeraddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetails",
            name="eventOrganizer",
            field=models.OneToOneField(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizer.organizer",
            ),
        ),
    ]
