# Generated by Django 4.2.2 on 2023-07-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0013_eventdetails_eventorganizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetails",
            name="eventOrganizer",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizer.organizer",
            ),
        ),
    ]
