# Generated by Django 4.2.2 on 2023-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0014_alter_eventdetails_eventorganizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetails",
            name="eventImage",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
