# Generated by Django 4.2.2 on 2023-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0015_eventdetails_eventimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetails",
            name="eventImage",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
