# Generated by Django 4.2.2 on 2023-07-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0016_alter_eventdetails_eventimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="currentTicket",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
