# Generated by Django 4.2.2 on 2023-07-24 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0017_ticket_currentticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="currentTicket",
            new_name="bookedTicket",
        ),
    ]
