# Generated by Django 4.2.2 on 2023-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0018_rename_currentticket_ticket_bookedticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetails",
            name="eventsecreteCode",
            field=models.CharField(default=True, max_length=200),
        ),
    ]
