# Generated by Django 4.2.2 on 2023-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0019_eventdetails_eventsecretecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetails",
            name="galleryImage1",
            field=models.ImageField(default="images/1.jpg", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="eventdetails",
            name="galleryImage2",
            field=models.ImageField(default="images/1.jpg", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="eventdetails",
            name="galleryImage3",
            field=models.ImageField(default="images/1.jpg", upload_to="images/"),
        ),
    ]
