# Generated by Django 4.2.2 on 2023-07-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_about",
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_email",
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_fburl",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_ldurl",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_name",
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_twurl",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_weburl",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="contact_number",
            field=models.IntegerField(default=True),
        ),
    ]
