# Generated by Django 4.2.2 on 2023-07-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userprofile_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="contact_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_fburl",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_ldurl",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_twurl",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_weburl",
            field=models.CharField(max_length=100),
        ),
    ]
