# Generated by Django 4.2.2 on 2023-07-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_cartitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
