# Generated by Django 4.2.2 on 2023-07-15 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_attendee"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="paymentStatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 15, 12, 25, 39, 296124),
                null=True,
            ),
        ),
    ]
