# Generated by Django 4.2.2 on 2023-07-16 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_cartitem_paymentstatus_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="payment_id",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 16, 9, 37, 30, 699644),
                null=True,
            ),
        ),
    ]
