# Generated by Django 4.2.2 on 2023-07-16 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_attendee_payment_id_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendee",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="attendee",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 16, 15, 28, 17, 436269),
                null=True,
            ),
        ),
    ]
