# Generated by Django 4.2.2 on 2023-07-16 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_remove_attendee_payment_id_attendee_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 16, 15, 42, 53, 163761),
                null=True,
            ),
        ),
    ]
