# Generated by Django 4.2.2 on 2023-07-16 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendee",
            old_name="payment_status",
            new_name="paymentStatus",
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 16, 15, 48, 37, 161898),
                null=True,
            ),
        ),
    ]
