# Generated by Django 4.2.2 on 2023-07-16 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0013_rename_payment_status_attendee_paymentstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="user",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 16, 17, 28, 29, 170700),
                null=True,
            ),
        ),
    ]
