# Generated by Django 4.2.2 on 2023-07-24 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_attendee_user_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 24, 9, 0, 0, 593830),
                null=True,
            ),
        ),
    ]
