# Generated by Django 4.2.2 on 2023-07-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_alter_attendee_secreatecode_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="attendenceStatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 24, 17, 19, 21, 665646),
                null=True,
            ),
        ),
    ]
