# Generated by Django 4.2.2 on 2023-07-25 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0019_attendee_attendencestatus_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 25, 17, 53, 17, 473275),
                null=True,
            ),
        ),
    ]
