# Generated by Django 4.2.2 on 2023-07-25 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 25, 20, 2, 17, 956275),
                null=True,
            ),
        ),
    ]
