# Generated by Django 4.2.2 on 2023-07-25 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="attendeZIP",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 25, 20, 18, 7, 576018),
                null=True,
            ),
        ),
    ]
