# Generated by Django 4.2.2 on 2023-07-25 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0023_alter_attendee_attendezip_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="attendeContact",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 25, 20, 22, 35, 729381),
                null=True,
            ),
        ),
    ]
