# Generated by Django 4.2.2 on 2023-09-21 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0025_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 9, 21, 22, 40, 28, 280202),
                null=True,
            ),
        ),
    ]
