# Generated by Django 4.2.2 on 2023-12-24 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0026_alter_attendee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 12, 24, 12, 2, 21, 784621),
                null=True,
            ),
        ),
    ]
